# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpJDaTddXPnxhJ2kd4AA9JBhPkrGXGZi
"""



"""# New Section"""

!pip install langchain faiss-cpu langchain-groq pypdf tiktoken
!pip install -U langchain-community

from google.colab import drive
drive.mount('/content/drive')

pdf_path = {
    "kelas1": [
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 7 BS press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 8 BG press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 8 BS press.pdf",
    ],
    "kelas2": [
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 4 BS press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 6 BG press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 6 BS press.pdf"
    ],

}

# 1️⃣ Import library
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# 2️⃣ Daftar file PDF per kelas
pdf_path = {
    "kelas1": [
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 7 BS press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 8 BG press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas1/Kelas I Tema 8 BS press.pdf",
    ],
    "kelas2": [
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 4 BS press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 6 BG press.pdf",
        "/content/drive/MyDrive/SEMESTER 7/MAGANG/chatbot/materi/sains/kelas2/Kelas 2 Tema 6 BS press.pdf"
    ],
}

# 3️⃣ Gabungkan semua dokumen dari semua file PDF
docs = []

for kelas, paths in pdf_path.items():
    print(f"📘 Memuat file untuk {kelas}...")
    for path in paths:
        loader = PyPDFLoader(path)
        data = loader.load()
        docs.extend(data)
        print(f"   ✅ {path.split('/')[-1]} berhasil dimuat ({len(data)} halaman)")

print(f"\nTotal dokumen berhasil dimuat: {len(docs)}")

# 4️⃣ Pecah teks menjadi potongan kecil agar bisa diproses model
splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
texts = splitter.split_documents(docs)
print(f"Total potongan teks: {len(texts)}")

# 5️⃣ Buat embedding (representasi numerik dari teks)
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# 6️⃣ Simpan semua teks ke database FAISS
db = FAISS.from_documents(texts, embeddings)
print("✅ Database FAISS berhasil dibuat!")

import os
from langchain_groq import ChatGroq
from langchain.chains import RetrievalQA

os.environ["GROQ_API_KEY"] = "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"

llm = ChatGroq(model="llama-3.3-70b-versatile")
retriever = db.as_retriever(search_kwargs={"k": 3})
qa = RetrievalQA.from_chain_type(llm=llm, retriever=retriever)

prompt = """
Kamu adalah guru SD yang membuat soal untuk murid kelas 1 berdasarkan materi sains dari buku pelajaran.

Gunakan isi materi berikut (hasil dari file PDF) untuk membuat 1 soal pilihan ganda dalam format berikut:

Soal:
A.
B.
C.
D.
✅ Jawaban Benar:
💡 Penjelasan:

Ketentuan:
- Gunakan bahasa Indonesia yang sederhana, sesuai untuk anak kelas 1 SD.
- Soal harus tentang sains dasar, seperti makhluk hidup, benda di sekitar, perubahan cuaca, air, udara, atau bumi.
- Pastikan jawaban dan penjelasan benar-benar sesuai isi materi dalam buku yang dianalisis.
"""

hasil = qa.run(prompt)
print("📚 Hasil Soal Sains:\n")
print(hasil)